version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: weekly
    commit_message:
      prefix: ⬆️ Upgrade
      include_scope: false
    default_labels:
      - dependabot
      - dependencies
